# Generated by Django 2.2 on 2020-05-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='branch',
            field=models.CharField(default='etrx', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='isapproved',
            field=models.BinaryField(default=0),
            preserve_default=False,
        ),
    ]
