# Generated by Django 2.2 on 2020-05-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_auto_20200504_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='branch',
            field=models.CharField(default='comps', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='isapproved',
            field=models.BooleanField(default='false'),
        ),
    ]
