# Generated by Django 2.2 on 2020-05-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_attendance_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='branch',
        ),
    ]
