# Generated by Django 2.2 on 2020-05-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_attendance_requbranch'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='isapproved',
            field=models.BooleanField(default='false'),
        ),
    ]
