# Generated by Django 2.2 on 2020-05-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0011_attendance_isapproved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='isapproved',
        ),
    ]
