# Generated by Django 2.2 on 2020-05-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0013_attendance_isapproved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='isapproved',
            field=models.BooleanField(default=False),
        ),
    ]
