# Generated by Django 2.2 on 2020-05-04 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0014_auto_20200504_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='isapproved',
        ),
    ]
