# Generated by Django 2.2 on 2020-05-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0016_attendance_isapproved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='requbranch',
            field=models.CharField(max_length=10),
        ),
    ]
